module.exports = [{
    category: "Features",
    emoji: "☑",
    id: "agreeChannel",
    label: "Aceptar canal",
    type: "channelID",
  }, {
    category: "Roles",
    emoji: "✔",
    id: "agreeRole",
    label: "Aceptar rol",
    type: "roleID",
  }, {
    category: "Automod",
    emoji: "🔗",
    id: "antiInvite",
    label: "Anti Invitaciones",
    type: "bool",
  }, {
    category: "Automod",
    emoji: "🚯",
    id: "antiSpam",
    label: "Anti Spam",
    type: "bool",
  }, {
    id: "assignableRoles",
    label: "Roles asignables",
    type: "roleArray",
  }, {
    category: "Roles",
    emoji: "👤",
    id: "autoRoles",
    label: "Roles automaticos",
    type: "roleArray",
    maximum: 5,
  }, {
    id: "disabledCategories",
    label: "Desactivar Categorias",
    type: "array",
  }, {
    id: "disabledCmds",
    label: "Desactivar Comandos",
    type: "array",
  }, {
    category: "Features",
    id: "easyTranslate",
    emoji: "🌍",
    label: "Traducción fácil",
    type: "bool",
    description: "Traduce automáticamente el contenido al que se reacciona con un emoji de bandera.",
  }, {
    category: "Automod",
    emoji: "⚒",
    id: "invitePunishments",
    label: "Castigo por invitaciones",
    type: "punishment",
  }, {
    category: "Logging",
    emoji: "👋",
    id: "leaveJoin",
    label: "Salir/Unirse Canal",
    type: "channelID",
  }, {
    category: "Logging",
    emoji: "✉",
    id: "joinMessage",
    label: "Mensaje de Bienvenida",
    type: "string",
    minimum: 1,
    maximum: 200,
  }, {
    category: "Logging",
    emoji: "🚪",
    id: "leaveMessage",
    label: "Mensaje de Despedida",
    type: "string",
    minimum: 1,
    maximum: 200,
  }, {
    category: "Logging",
    emoji: "📄",
    id: "eventLogging",
    label: "Canal de Logs de eventos",
    type: "channelID",
  }, {
    category: "Logging",
    emoji: "📜",
    id: "messageLogging",
    label: "Canal de Logs de mensajes",
    type: "channelID",
  }, {
    category: "Logging",
    emoji: "📰",
    id: "memberLogging",
    label: "Canal de Logs de miembros",
    type: "channelID",
  }, {
    category: "Logging",
    emoji: "📃",
    id: "modLogging",
    label: "Canal de Logs de mod",
    type: "channelID",
  },
  {
    category: "Logging",
    emoji: "📵",
    id: "ignoredLoggingChannels",
    label: "Canales de Logs ignorados",
    type: "channelArray",
  }, {
    category: "Automod",
    emoji: "💬",
    id: "msgOnPunishment",
    label: "Mensaje de castigo",
    type: "bool",
  }, {
    category: "Roles",
    emoji: "🔕",
    id: "mutedRole",
    label: "Rol Mute",
    type: "roleID",
  }, {
    category: "Features",
    emoji: "💣",
    id: "snipingEnable",
    label: "Ultimo mensaje",
    type: "bool",
  }, {
    category: "Features",
    emoji: "🚫",
    id: "snipingIgnore",
    label: "Canales de Snipe ignorados",
    type: "channelArray",
  }, {
    category: "Features",
    emoji: "🔗",
    id: "snipingInvites",
    label: "Invitaciones Snipe",
    type: "bool",
  }, {
    category: "Features",
    emoji: "⛔",
    id: "snipingPermission",
    label: "Publico Snipe",
    type: "bool",
  }, {
    category: "Roles",
    emoji: "🔨",
    id: "staffRole",
    label: "Rol del Staff",
    type: "roleID",
  }, {
    category: "Features",
    emoji: "🔢",
    id: "pinAmount",
    label: "Cantidad de Fijados",
    type: "number",
  }, {
    category: "Features",
    emoji: "📍",
    id: "pinChannel",
    label: "Canal de Fijación",
    type: "channelID",
  }, {
    category: "Features",
    emoji: "📌",
    id: "pinEmoji",
    label: "Emoji de Fijación",
    type: "emoji",
  }, {
    category: "Features",
    emoji: "🗣",
    id: "pinSelfPinning",
    label: "Auto Fijación ",
    type: "bool",
  }, {
    id: "prefix",
    label: "Prefix",
    type: "string",
    minimum: 1,
    maximum: 15,
  }, {
    category: "Automod",
    emoji: "🛠",
    id: "spamPunishments",
    label: "Castigos de spam",
    type: "punishment",
  }, {
    category: "Automod",
    emoji: "🔢",
    id: "spamThreshold",
    label: "Spam Límite",
    minimum: 5,
    maximum: 10,
    type: "number",
  }, {
    category: "Roles",
    emoji: "☑",
    id: "verifiedRole",
    label: "Rol verificado",
    type: "roleID",
  }, {
    category: "Profile",
    id: "bio",
    type: "string",
    minimum: 1,
    maximum: 200,
  }, {
    category: "Profile",
    id: "pronouns",
    type: "selection",
  }, {
    category: "Profile",
    id: "timezone",
    type: "autofill",
  }, {
    category: "Profile",
    id: "timezoneHide",
    type: "bool",
  },
];
